### ISSUE TITLE
Simple example

### ISSUE THREAD

**Issue by xgrommx** [blesh/RxEmber#6]
@blesh Could you please provide some full simple example how can I use it with ember v1.11.0 and es6 syntax together?

**Comment by blesh** [comment]
Really, the *meat* of this utility is `bindTo` as it can be used with Components:

```js
var { computed } = Rx
var { bindTo } = Rx.Ember.helpers;

export default Ember.Component.extend({
  fooStream: computed(() => Observable.interval(1000).map(n => 'foo ' + n)),

  foo: bindTo('fooStream');
});
```

What the above example does is setup a property `fooStream` that is an observable stream of `"foo 1" ... "foo 2" ... "foo 3"` that ticks in once every 1000ms (1 sec), then it sets up a property `foo`, that when you first `get("foo")` will subscribe to the stream at `fooStream` and set up disposal of that subscription to occur when the component's `willDestroy` is fired.

Does that make sense?

**Comment by blesh** [comment]
I'm not sure where/how would be best to add an example to the project itself. I think the docs just need improvement.

**Comment by xgrommx** [comment]
Yes, I create a simple example already. I cannot find ```computed``` in https://github.com/blesh/RxEmber/blob/master/lib/rx-ember.js. Maybe do you mean ```computedObservable```?

**Comment by blesh** [comment]
Oops... I meant `var { computed } = Ember` ... I was moving too fast.

**Comment by blesh** [comment]
updated my example above.

`fooStream` is just an ordinary Ember property that returns an Observable. technically, you could just put it straight on the property, just as long as you don't use Rx's `publish()`, because then it will only subscribe once.

```js
var { computed } = Ember;
var { Observable } = Rx;
var { bindTo } = RxEmber.helpers;

export default Ember.Component.extend({
  fooStream: Observable.interval(1000).map(n => 'foo ' + n),

  foo: bindTo('fooStream');
});
```
